dataset_path: data
save_dir: preprocessed_data
seed: 42
num_epoch: 3
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 8
    shuffle: false
  test:
    batch_size: 1
    shuffle: false
train:
  no_batch_norm: false
  initial_learning_rate: 0.01
  low_lr: 0.001
  low_lr2: 0.0001
  weight_decay: 0.0001
  epochs: 10
